---
output:
  pdf_document: default
  html_document: default
---
#1. Create a data frame using the table below.

#a. Write the codes.
HouseholdData <- data.frame (

  Responders = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20),
  Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,1),
  FathersOccupation = c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),
  PersonsAtHome = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),
  SiblingsAtSchool = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),
  TypeOfHouses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)

)
#b. Describe the data. Get the structure or the summary of the data
#20 observations and 6 variables.
str(HouseholdData)
#Summary of every variables inside HouseholdData
summary(HouseholdData)

#c. Is the mean number of siblings attending is 5?
#No it's 2.95
meanNumSiblingsAttending <- mean(HouseholdData$SiblingsAtSchool)
meanNumSiblingsAttending

#d. Extract the 1st two rows and then all the columns using the subsetting functions. Write the codes and its output.
FirstTwoRows <- HouseholdData[1:2]
FirstTwoRows

#Output:
#Responders Sex
#1           1   2
#2           2   2
#3           3   1
#4           4   2
#5           5   2
#6           6   2
#7           7   2
#8           8   2
#9           9   2
#10         10   2
#11         11   1
#12         12   2
#13         13   2
#14         14   2
#15         15   2
#16         16   2
#17         17   2
#18         18   2
#19         19   2
#20         20   1

#e. Extract 3rd and 5th row with 2nd and 4th column. Write the codes and its result.

ThirdToFifth <- HouseholdData[c(3, 5), c(2, 4)]
ThirdToFifth 


#Output:
#Sex PersonsAtHome
#3   1             3
#5   2             5
 
#f. Select the variable types of houses then store the vector that results as types_houses. Write the codes.

types_houses <- HouseholdData$TypeOfHouses
types_houses

#Output:
#[1] 1 2 3 1 1 3 3 1 2 3 2 3 2 2 3 3 3 3 3 2

#g. Select only all Males respondent that their father occupation was farmer. Write the codes and its output.

MaleFarmers <- HouseholdData[HouseholdData$Sex == 1 & HouseholdData$FathersOccupation == 1, ]
MaleFarmers

#Output:
# Responders Sex FathersOccupation PersonsAtHome SiblingsAtSchool TypeOfHouses
#20         20   1                 1             6                2            2

#h. Select only all females respondent that have greater than or equal to 5 number of siblings attending school. Write the codes and its outputs.

FemalesRespondent <- HouseholdData[HouseholdData$Sex == 2 & HouseholdData$SiblingsAtScchool >= 5 ]
FemalesRespondent

#Output:
#data frame with 0 columns and 20 rows

#2. Write a R program to create an empty data frame. Using the following codes:

df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))


#a. Describe the results.
#This software will build a blank data frame using the column names and data types you specify when you run it. The structure of the empty data frame is then printed using the str() function. 

#3. Create a .csv file of this. Save it as HouseholdData.csv

HouseholdsData <- data.frame(
  Respondents = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  Sex = c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male"),
  FathersOccupation = c(1, 2, 3, 3, 1, 2, 2, 3, 1, 3),
  PersonsAtHome = c(5, 7, 3, 8, 6, 4, 4, 2, 11, 6),
  SiblingsAtSchool = c(2, 3, 0, 5, 2, 3, 1, 2, 6, 2),
  TypesOfHouses = c("Wood", "Congrete", "Congrete", "Wood", "Semi-Congrete", "Semi-Congrete","Wood","Semi-Congrete","Semi-Congrete","Congrete")
)


write.csv(HouseholdsData, file = "HouseholdData.csv")
write.csv

#a. Import the csv file into the R environment. Write the codes.
read.csv("HouseholdData.csv")


#b. Convert the Sex into factor using factor() function and change it into integer.[Legend:Male = 1 and Female = 2]. Write the R codes and its output.

MaleFemale <- c("Male", "Female")
FactoredMaleFemale<-HouseholdsData$Sex <- factor(HouseholdsData$Sex, levels = c(MaleFemale), labels = c(1, 2))
FactoredMaleFemale


#Output:
#[1] 1 2 2 1 1 2 2 1 2 1
#Levels: 1 2

#c. Convert the Type of Houses into factor and change it into integer. [Legend: Wood= 1; Congrete = 2; Semi-Congrete = 3]. Write the R codes and its output.

TypesOfHouse <- c("Wood", "Congrete", "Semi-Congrete")
HouseholdsData$TypesOfHouses <- factor(HouseholdsData$TypesOfHouses, levels = c(TypesOfHouse),labels = c(1, 2, 3))
factoredTypesofHouses <- HouseholdsData$TypesOfHouses
factoredTypesofHouses


#Output:
#[1] 1 2 2 1 3 3 1 3 3 2
#Levels: 1 2 3

#d. On father’s occupation, factor it as Farmer = 1; Driver = 2; and Others = 3. What is the R code and its output?

HouseholdsData$FathersOccupation <- factor(HouseholdsData$FathersOccupation, levels = c(1, 2, 3), labels = c("Farmer", "Driver", "Others"))
FactoredOccupation <- HouseholdsData$FathersOccupation
FactoredOccupation

#Output:
#[1] Farmer Driver Others Others Farmer Driver Driver Others Farmer Others
#Levels: Farmer Driver Others


#e. Select only all females respondent that has a father whose occupation is driver. Write the codes and its output.

DriverFathers <- HouseholdsData[HouseholdsData$Sex == "Female" & HouseholdsData$FathersOccupation == 2, ]
DriverFathers

#Output:
#[1] Respondents       Sex               FathersOccupation PersonsAtHome  
#[5] SiblingsAtSchool  TypesOfHouses    
#<0 rows> (or 0-length row.names)

#f. Select the respondents that have greater than or equal to 5 number of siblings attending school. Write the codes and its output.

Respondents <- HouseholdsData [HouseholdsData$SiblingsAtSchool >= 5,]
Respondents

#Output: 
# Respondents Sex FathersOccupation PersonsAtHome SiblingsAtSchool
#4           4   1            Others             8                5
#9           9   2            Farmer            11                6
#  TypesOfHouses
#4             1
#9             3


#4. Interpret the graph.
#July 15, 2020 is the highest negative Sentiments of tweets per day whilst July 20, 2020 is the second negative, Though july 20,2020 has the highest positive Sentiments of tweets per day whils july 15,2020 has the highest neutral whilst july 20,2020 is the second in neutral
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
